
#include "stm32f0xx.h"

void SystemInit(void)
{
	RCC->AHBENR 	|=	RCC_AHBENR_GPIOAEN;

	RCC->APB2ENR	|=	RCC_APB2ENR_SPI1EN |
						RCC_APB2ENR_USART1EN |
						RCC_APB2ENR_SYSCFGEN;

	RCC->APB1ENR	|=	RCC_APB1ENR_TIM3EN;

	GPIOA->MODER	|=	GPIO_MODER_MODER0_0 |
						GPIO_MODER_MODER1_0 |
						GPIO_MODER_MODER2_0 |

						GPIO_MODER_MODER4_0 |
						GPIO_MODER_MODER5_1 |
						GPIO_MODER_MODER6_1 |
						GPIO_MODER_MODER7_1 |

						GPIO_MODER_MODER9_1 |
						GPIO_MODER_MODER10_1 |

						GPIO_MODER_MODER13_1 |
						GPIO_MODER_MODER14_1;

	GPIOA->OSPEEDR	|=	GPIO_OSPEEDR_OSPEEDR4_0 | GPIO_OSPEEDR_OSPEEDR4_1 |
						GPIO_OSPEEDR_OSPEEDR5_0 | GPIO_OSPEEDR_OSPEEDR5_1 |
						GPIO_OSPEEDR_OSPEEDR6_0 | GPIO_OSPEEDR_OSPEEDR6_1 |
						GPIO_OSPEEDR_OSPEEDR7_0 | GPIO_OSPEEDR_OSPEEDR7_1 |

						GPIO_OSPEEDR_OSPEEDR9_0 | GPIO_OSPEEDR_OSPEEDR9_1 |
						GPIO_OSPEEDR_OSPEEDR10_0 | GPIO_OSPEEDR_OSPEEDR10_1 ;

	GPIOA->AFR[1]	|=  1 << GPIO_AFRH_AFRH1_Pos |
						1 << GPIO_AFRH_AFRH2_Pos;

	GPIOA->BSRR		= 	GPIO_BSRR_BS_4;

	GPIOA->BRR		=	GPIO_BRR_BR_2;

	SPI1->CR2		=	SPI_CR2_SSOE |
						SPI_CR2_DS_0 | SPI_CR2_DS_1 | SPI_CR2_DS_2 |
						SPI_CR2_FRXTH;

	SPI1->CR1		=	SPI_CR1_MSTR |
						SPI_CR1_SPE;

	USART1->BRR		=	8000000 / 9600;

	USART1->CR1		=	USART_CR1_UE |
						USART_CR1_TE |
						USART_CR1_RE |
						USART_CR1_RXNEIE;

	SYSCFG->EXTICR[0] = SYSCFG_EXTICR1_EXTI3_PA;

	EXTI->IMR 		= 	EXTI_IMR_IM3;
	EXTI->FTSR 		= 	EXTI_FTSR_FT3;
	EXTI->PR 		= 	EXTI_PR_PR3;

	TIM3->PSC		= 8000 - 1;
	TIM3->ARR		= 3000;				//1000 - 1;
	TIM3->DIER		= TIM_DIER_UIE;

	NVIC_EnableIRQ(EXTI2_3_IRQn);
	NVIC_EnableIRQ(USART1_IRQn);
	NVIC_EnableIRQ(TIM3_IRQn);
}

void SystemCoreClockUpdate (void)
{

}

